version: "3"

services:
  app:
    build: 
      context: ./node
    image: fernandofonseca/node-desafio:prod
    container_name: app
    volumes: 
      - ./node:/usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    networks:
      - desafio-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-network

  nginx:
    build: 
      context: ./nginx
    image: fernandofonseca/nginx-desafio:prod
    container_name: nginx
    networks:
      - desafio-network
    ports:
      - "8080:80"


networks:
  desafio-network:
    driver: bridge